FROM ubuntu:trusty
MAINTAINER anon

RUN apt-get update
RUN apt-get install -y software-properties-common

# Install java7 - FROM java:7 would be faster and simpler here, but just following requirements
RUN add-apt-repository -y ppa:webupd8team/java
RUN apt-get update
RUN echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN apt-get install -y oracle-java7-installer
ADD /target/packageindexer.jar /packageindexer.jar
CMD ["java", "-jar", "/packageindexer.jar"]